"""
/***************************************************************************
 Threader
                                 A QGIS plugin
 Bug example for threading crash on disco/qt5.12
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-15
        copyright            : (C) 2019 by F. Meckel
        email                : friedrich.meckel@ambrosys.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):  # pylint: disable=invalid-name
    """Load Threader class from file Threader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .labeling_test import LabelingTest
    return LabelingTest(iface)
